#!/bin/bash
set -eo pipefail

if ! type -pP bita > /dev/null ; then
   echo "Could not find bita! Please see the README."
   exit 2
fi

if ! type -pP jq > /dev/null ; then
   echo "Could not find jq! Please see the README."
   exit 2
fi


MANIFEST_URL='https://updates.roseonlinegame.com'

update_lines=$(curl --silent -L "$MANIFEST_URL"'/manifest.json' | jq -r '.files | [ .[] | [ .[] ] | [ .[0], .[1], ( .[2] | @sh ), .[3] ] ] | .[] | @sh')

to_hash_str () {
   the_array=("$@")
   for i in "${the_array[@]}" ; do
      printf "%02x" "$i"
   done
   printf '\n'
}

if [ ! -f "rose.vfs" ] ; then
   echo "Could not find rose.vfs, are you running Swamp ROSE updater in the ROSE source folder? Current directory is: $(pwd)"
   exit 1
fi

files_to_skip=()
if [ -f "no_update_list.txt" ] ; then
   declare -a files_to_skip=($(cat "no_update_list.txt"))
fi

while read -r update_line; do
   declare -a the_array="($update_line)"
   path_tail=${the_array[0]}
   filename=${the_array[1]}
   declare -a almost_hash="(${the_array[2]})"
   the_hash=$(to_hash_str "${almost_hash[@]}")
   filesize=${the_array[3]}
   archive_url="$MANIFEST_URL""/$path_tail"
   if [[ " ${files_to_skip[*]} " == *"$filename"* ]] ; then
      echo "Not updating $filename by explicit request."
      continue
   fi
   # Alternatively, one could parse the regular output of b2sum for all files at once.
   # The performance gain would be about 0.5 seconds on 5 seconds total, while
   # complicating the implementation. We therefore keep it simple, and call b2sum multiple times
   if ! echo "$the_hash $(pwd)/$filename" | b2sum --check --status - ; then
      echo "Updating $filename ..."
      filedir="$(dirname "$(pwd)/$filename")"
      if [ ! -d "$filedir" ] ; then
         echo "Creating possibly deleted directory $filedir"
         mkdir -p "$filedir"
      fi
      if bita clone --seed-output "$archive_url" "$(pwd)/$filename" ; then
         echo "Succesfully updated $filename"
         echo
      else
         echo "Bita failed!"
         exit $?
      fi
   fi
done <<< "$update_lines"

echo "ROSE Online is up to date."


