#!/bin/bash

MANIFEST_URL='https://updates.roseonlinegame.com'

update_lines=$(curl --silent -L "$MANIFEST_URL"'/manifest.json' | jq -r '.files | [ .[] | [ .[] ] | [ .[0], .[1], ( .[2] | @sh ), .[3] ] ] | .[] | @sh')

to_hash_str () {
   the_array=("$@")
   for i in "${the_array[@]}" ; do
      printf "%02x" "$i"
   done
   printf '\n'
}

while read -r update_line; do
   declare -a the_array="($update_line)"
   path_tail=${the_array[0]}
   filename=${the_array[1]}
   if [ ! -f "$filename" ] ; then
      echo "Could not find $filename, are you running Swamp ROSE updater in the ROSE source folder?"
      exit 1
   fi
   declare -a almost_hash="(${the_array[2]})"
   the_hash=$(to_hash_str "${almost_hash[@]}")
   filesize=${the_array[3]}
   archive_url="$MANIFEST_URL""/$path_tail"
   if ! echo "$the_hash $(pwd)/$filename" | b2sum --check --status - ; then
      echo "Updating $filename ..."
      bita clone --seed-output "$archive_url" "$filename"
      echo
   fi
done <<< "$update_lines"



